### PR TITLE
Htaccess fix

### PR DESCRIPTION
**Pull request by Louis-coding-UGNG**
updated htaccess rules and redirection path after deleting a song to relative paths instead of domain root

### CODE REVIEW

**Comment by bloodybowlers** [comment]
Ok, I'll test this on my install and then merge.

**Comment by bloodybowlers** [comment]
Unfortunately it's still not working.

- When I login, I get redirected to the **song not found** page.
- When I try to view the **404 page** (on incorrect url) : it won't redirect, instead it displays the htaccess line **"music.php?action=NotFound404"** in the browser...

This htaccess thing is driving me crazy...

**Comment by Louis-coding-UGNG** [comment]
> * When I login, I get redirected to the **song not found** page.

Can't confirm this on my test site https://ng.4str.in/test2 - login works, and after login the 404 page comes up as expected.
 
> * When I try to view the **404 page** (on incorrect url) : it won't redirect, instead it displays the htaccess line **"music.php?action=NotFound404"** in the browser...

Confirmed. But this seems more like a problem of the error page, it happens with the original code
`ErrorDocument 404 /music.php?action=NotFound404` (OK, this gives a "error page not found")
as well as with my modified code
`ErrorDocument 404 music.php?action=NotFound404`
Calling the error page directly (https://ng.4str.in/music.php?action=NotFound404) works fine when login is not required. With login required I only get the login page when calling the error page without being logged in; after login it is OK.
So it looks like a conflict between _const IsLoginRequired_ and the _action=NotFound404_
Similar behaviour without mod_rewrite, btw.

**Comment by bloodybowlers** [comment]
The behavior I described happen if you install in the root dir.  
I don't know what to do... The **rewritebase** should be the solution but with my root install it's not working.

**Comment by bloodybowlers** [comment]
[Found this](https://stackoverflow.com/questions/704102/how-does-rewritebase-work-in-htaccess). In the doc, it seems RewriteBase works as we expect it to work....

**Comment by Louis-coding-UGNG** [comment]
So should we perhaps open a new issue for the custom 404 error page?
And probably deactivate the htaccess rule `ErrorDocument 404 music.php?action=NotFound404` for the time being?

>The behavior I described happen if you install in the root dir.

This is odd. I just copied the contents from ng.4str.in/test2 to https://ugng.4str.in, adjusted the subdir in config.php and htaccess - and it seems to work as expected (feel free to test yourself).
Calling a wrong url like https://ugng.4str.in/bogus only shows the text "music.php?action=NotFound404"; calling https://ugng.4str.in/songbook/bogus brings up the desired 404 song

**Comment by bloodybowlers** [comment]
I understood what cause this a few seconds ago.

The thing that made the bug is : 

**ErrorDocument doesn't respect rewritebase. It's not part of mod_rewrite.**

I changed the htaccess.txt + README to show which lines to modify, and I'm in the process of taking your changes and merging.

Finally :D

**Comment by bloodybowlers** [comment]
I had to resolve lots of conflict with the **PublicMode** branch so I added the htaccess fix to that branch. I'll close this PR and we can continue on #63.

**Pull request closed without merging**
