### PR TITLE
Added x_UGNG_category + sorting on the song list page

### LINKED ISSUE #13: Multiple songbook sorting mode (by title, artist, ...)
Multiple songbook sorting mode (by title, artist, ...)

### PR DESCRIPTION
**Pull request by bloodybowlers**
As requested in #18 and should close #13.
It's now ready to add more sorting mode if needed.

### CODE REVIEW

**Comment by bloodybowlers** [comment]
@Louis-coding-UGNG 
I tested this with mod_rewrite ENABLED, not without it.

**Comment by Louis-coding-UGNG** [comment]
Just tested: it doesn't work without rewriting, neither in root nor in a subdirectory - is that a bug or a given fact for some reason?

And could you include sorting by song title as well?

**Comment by bloodybowlers** [comment]
> is that a bug or a given fact for some reason?

I didn't test without rewriting so it's probably a bug.

The fact that each modification needs to be tested with and without rewriting is starting to be a **real** pain, imho.

**mod_rewrite** is so common in all web projects, it's available on all shared hosting because of that, that I think I'll drop the support for "old ugly php file in the url" and make mod_rewrite a requirement.

It'll simplify dev but not only. User won't have to fiddle and decide to use it or not...

Edit :  
> And could you include sorting by song title as well?

Sure

**Comment by Louis-coding-UGNG** [comment]
> make mod_rewrite a requirement

Fine with me, I only use shared hosting with Apache so mod_rewrite is in any case always available for me. I have no idea how many people want tu use UGNG on other webservers without rewrite support - nor do I have a clue how complicated it would be to adapt the config for other webservers...

**Comment by bloodybowlers** [comment]
Ok, I'll add commits to this PR to wipe non mod_rewrite support then.
I'll let you know so you could test it with your subfolder setup.

**Comment by bloodybowlers** [comment]
@Louis-coding-UGNG 

Ok, I added the sorting by title.
Major change too : I dropped NON mod_rewrite support.  

I tested on my root dir install (not in a subfolder).

To test, you need to :  
- Make sur you added the "**songbooksorted**" directive to your **.htaccess** file
- Updated your **config.php** to remove the useless **UseModRewrite** const
- Be careful when you want to fetch this branch because I rewrote history :p  Use **fetch** then **reset --hard** your local branch

**Comment by Louis-coding-UGNG** [comment]
OK, test site is (temporarily) on https://ng.4str.in/subdir, freshly built on commit 6c298a9

Some findings:
- sometimes the Subdirectory from config is used/needed without trailing slash, sometimes with trailing slash; the behaviour is somewhat inconsistent here (I'll try to find some more time for more detailed investigation, for the time being it is set to `const Subdirectory = '/subdir';`)
It appears that the sorting links (and the songook link on the song page) do not automagically add the trailing slash and are thus broken, e.g. `<a href="/subdirsongbooksorted/category">Category</a>`
- all song links in the list are absolute and missing the Subdirectory (sort by category on the test site and you'll see): `echo '  <a href="'.$s->Uri.'"'.(Config::openSongInNewTab?' target=_blank':'').'>` 
  - I modified the "artist" list (views/song-list-detailed.php, line 47) to `echo '  <a href="'.(defined('Config::Subdirectory') ? Config::Subdirectory:'').$song->Uri.'"'.(Config::openSongInNewTab?' target=_blank':'').'>`,
  - the "title" list (line 75) to `echo '  <a href=".'.$song->Uri.'"'.(Config::openSongInNewTab?' target=_blank':'').'>` (added a leading '.' after _href="_ for relative path)
- I seem unable to open a title sorted song, the link structure https://ng.4str.in/subdir/songbooksorted/songbook/dirty_old_town.the_pogues.ugs632935 throws me back to the artist sorted overview; a working link would be https://ng.4str.in/subdir/songbook/dirty_old_town.the_pogues.ugs632935

Will continue testing later, time is a scarce resource atm....

**Comment by bloodybowlers** [comment]
> * sometimes the Subdirectory from config is used/needed without trailing slash, sometimes with trailing slash; the behaviour is somewhat inconsistent here (I'll try to find some more time for more detailed investigation, for the time being it is set to `const Subdirectory = '/subdir';`)

Yep, we need a consistant use of this const. We should make a global pass on the code and decide how to use it, and fix the code. I think the slash before the subdir is mandatory (see below).

>   It appears that the sorting links (and the songook link on the song page) do not automagically add the trailing slash and are thus broken, e.g. `<a href="/subdirsongbooksorted/category">Category</a>`

Ok. This trailing slash problem happen when the subdir is set, so I think the good thing to do is use **/subdir** in the **Subdir const**, as you did. The code will then works like if it's installed in **root** with **/**.

> * all song links in the list are absolute and missing the Subdirectory (sort by category on the test site and you'll see): `echo '  <a href="'.$s->Uri.'"'.(Config::openSongInNewTab?' target=_blank':'').'>`

It seems that the indexing process store the hard path into its database (the songlist cache file).  
I think that when you change the subdirectory configuration, you should rebuild (**reindex**) the cache.
 

> * I seem unable to open a title sorted song, the link structure https://ng.4str.in/subdir/songbooksorted/songbook/dirty_old_town.the_pogues.ugs632935 throws me back to the artist sorted overview; a working link would be https://ng.4str.in/subdir/songbook/dirty_old_town.the_pogues.ugs632935

It is working  on my root install so I guess it's either a **.htaccess** (but if category sorting is working, that's not the problem) problem or the index building **hard stored path** I talked about earlier ?
 
> Will continue testing later, time is a scarce resource atm....

Yes, same here. If I find the time I'll setup a "subdir" install to test directly...

**Comment by Louis-coding-UGNG** [comment]
> Ok. This trailing slash problem happen when the subdir is set, so I think the good thing to do is use **/subdir** in the **Subdir const**, as you did. The code will then works like if it's installed in **root** with **/**.

If _Config::Subdirectory_ is defined check whether it ends with "/" and add a slash if not already present - could that be done already in the config.php (_public static function Init()_)?
That should heal all links built with MakeUri already.

The hard stored path in cache caused my other troubles: after I manually deleted the chache contents it was automatically rebuilt and the song links are now correct. duh, stupid me.

In fact it appears that defining `const Subdirectory = '/subdir/';` (with a trailing slash) and rebuilding the cache was the solution for all my findings above, your original code works as intended.

**Comment by Louis-coding-UGNG** [comment]
Ok. Just to prove my previous fault I reinstalled this branch (6c298a9) from scratch, changed the paths in .htaccess and defined '/subdir/' in config.php.
👍 Initial cache is built on first site visit and includes the correct full path for every song
👍 Song list can be sorted by artist, category and title
👍 editor is accessible after admin login
bottom line: works as designed once you do it right

One minor glitch (I wouldn't really call it a bug) was basically already covered in #29: the "Songbook" link in editor goes back to the default songbook page, not to the previously selected sorting. But that can be healed by opening songs in new tabs - should that probably be true by default?

And artist sorting is case-sensitive (as commented on issue #13).

**Comment by bloodybowlers** [comment]
> If _Config::Subdirectory_ is defined check whether it ends with "/" and add a slash if not already present - could that be done already in the config.php (_public static function Init()_)?
> That should heal all links built with MakeUri already.

I just re-read the README, and it was specified that the subdirectory should ends with a slash :P  
Anyway, **I modified config.php** (you **should do it too** because it's not versionned) and **config.php_example** to add a getter for the subdirectory and do some magic for the missing trailing slash. It should prevent all future problems.

 
> The hard stored path in cache caused my other troubles: after I manually deleted the chache contents it was automatically rebuilt and the song links are now correct. duh, stupid me.

Yes, hard stored path in the cache is a pain, and I don't see why the original UkeGeeks did that.  Maybe we should open an issue to remove the hard coding of the path.

**Comment by bloodybowlers** [comment]
> One minor glitch (I wouldn't really call it a bug) was basically already covered in #29: the "Songbook" link in editor goes back to the default songbook page, not to the previously selected sorting. But that can be healed by opening songs in new tabs - should that probably be true by default?

Yep, I'll commit a config.php_example with **openinnewtab** enabled by default.

**Pull request merged**
