### PR TITLE
Added real Public/Private mode to the site

### LINKED ISSUE #16: Public read only mode
*Actually* there is no real "public read only" mode. Either **everything is public** (read/write) or **everything require login** (with read/write separation for guest/admin).

It would be useful if one want a songbook public but wants to block others things (NO adding of songs or other "sensible" operations (reindex, ...).

### PR DESCRIPTION
**Pull request by bloodybowlers**
Now the site can be :
- private (login required = true)
- public (login required = false)

In public mode, people can VIEW songs but can't modify anything else.
Users can now login if they want to add songs/reindex.

It's hacky, the whole auth/login code should be
rewritten from scratch... but, hey !

Should _fiiiinalyyyyy_ implements/fix #16 !

### CODE REVIEW

**Comment by bloodybowlers** [comment]
@Louis-coding-UGNG  
I'll merge to master when you'll have some time to test this because it's an important change.

I did multiple tests on my side, **public** mode, **private** mode. Everything seems to work as intended.  
In public mode I tried to reindex (it was refused). But we **should** try to **add song** too just to be sure... (ajax call ? or get ?)

**Comment by Louis-coding-UGNG** [comment]
OK, set up a first test as public mode on https://ng.4str.in/pub
Guest can log in, but doesn't seem to have any additional rights after login: no edit, no add, only view and toggle options/layout
Admin can log in and has full rights incl. reindex.

Which brings me to the first "issue": logout should land on the same index page like an initial call. Sounds weird, I know. Means: in public mode, logout should jump back to the songbook directory (= the very page you see when first visting the site) instead of the login page.

Will setup another one in root later....

**Comment by bloodybowlers** [comment]
> Which brings me to the first "issue": logout should land on the same index page like an initial call. Sounds weird, I know. Means: in public mode, logout should jump back to the songbook directory (= the very page you see when first visting the site) instead of the login page.

Sure we can do that. It depends. Maybe if you were logged as a user, you wanted to switch to admin to add song ? Then, in that case, it makes sense to stay on the login page ?  
Maybe we can just add a link to the main page ? (in fact, it already exists if you click the title of the songbook on the login page) ?

**Comment by Louis-coding-UGNG** [comment]
> it already exists if you click the title of the songbook on the login page

Never noticed that before - it didn't even come to my mind to try that :-/

Anyway, I would still land the logout on the default main page. In case I am logged in as user and want to switch to admin mode (why would I do that instead of logging in as admin straight away?) I only have one more click on "Login" from the songbook page of the public site.
I would expect the user/admin switch to be the exception rather than the most common move, so it will be worth the additional click - the majority of users will be happy landing on the start page.

And if the site is set to private you'll be directed to the login page anyway.

**Comment by bloodybowlers** [comment]
Ok, sold.

**Comment by bloodybowlers** [comment]
Merged to master.

**Pull request closed without merging**
